### ISSUE TITLE
error in jmx2dsl.jar - null/empty values in headers causes NPE

### ISSUE THREAD

**Issue by gOOrcio** [abstracta/jmeter-java-dsl#133]
While trying to convert a test plan having headers value empty (screenshot), conversion is not possible due to NPE.
This is a valid behaviour of my system under test to send/accept headers with empty values. 

Would it be possible to handle that NPE or add a flag to control if NPE should be thrown here?

![image](https://user-images.githubusercontent.com/42868457/185170955-daa7248e-e7ac-49ea-ab00-64bc7b145832.png)

`java.lang.NullPointerException
        at us.abstracta.jmeter.javadsl.codegeneration.MethodParam.buildStringLiteral(MethodParam.java:86)
        at us.abstracta.jmeter.javadsl.codegeneration.params.StringParam.buildCode(StringParam.java:23)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildParamsCode$12(MethodCall.java:386)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildParamsCode(MethodCall.java:388)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildCode(MethodCall.java:357)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildChainedCode$14(MethodCall.java:394)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildChainedCode(MethodCall.java:396)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildCode(MethodCall.java:364)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.lambda$buildCode$3(ChildrenParam.java:79)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.buildCode(ChildrenParam.java:81)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildParamsCode$12(MethodCall.java:386)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildParamsCode(MethodCall.java:388)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall$ChildrenMethodCall.buildCode(MethodCall.java:226)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildChainedCode$14(MethodCall.java:394)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildChainedCode(MethodCall.java:396)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildCode(MethodCall.java:364)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.lambda$buildCode$3(ChildrenParam.java:79)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.buildCode(ChildrenParam.java:81)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildParamsCode$12(MethodCall.java:386)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildParamsCode(MethodCall.java:388)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildCode(MethodCall.java:357)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.lambda$buildCode$3(ChildrenParam.java:79)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.params.ChildrenParam.buildCode(ChildrenParam.java:81)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.lambda$buildParamsCode$12(MethodCall.java:386)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildParamsCode(MethodCall.java:388)
        at us.abstracta.jmeter.javadsl.codegeneration.MethodCall.buildCode(MethodCall.java:357)
        at us.abstracta.jmeter.javadsl.codegeneration.DslPerformanceTest.buildTestMethodCall(DslPerformanceTest.java:93)
        at us.abstracta.jmeter.javadsl.codegeneration.DslPerformanceTest.buildCode(DslPerformanceTest.java:29)
        at us.abstracta.jmeter.javadsl.codegeneration.DslCodeGenerator.generateCodeFromJmx(DslCodeGenerator.java:149)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.call(Jmx2Dsl.java:44)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.call(Jmx2Dsl.java:17)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.main(Jmx2Dsl.java:56)`

**Comment by rabelenda** [comment]
[This release](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.64.3) should fix the issue.

Regards

**Comment by gOOrcio** [comment]
Works fine, thanks a lot! Swift action much appreciated!
