### ISSUE TITLE
Seeing Problem loading XML from jmx file

### ISSUE THREAD

**Issue by vrrocket** [abstracta/jmeter-java-dsl#134]
While trying to generate DSL file from jmx using jmx2dsl.jar, below exception is thrown

`java.lang.IllegalArgumentException: Problem loading XML from:'<Path_to_jmx_file'.
Cause:
ClassNotFoundException: org.apache.commons.collections4.map.LRUMap

 Detail:com.thoughtworks.xstream.converters.ConversionException:
---- Debugging information ----
cause-exception     : java.lang.NoClassDefFoundError
cause-message       : org/apache/commons/collections4/map/LRUMap
first-jmeter-class  : org.apache.jmeter.util.JSR223TestElement.<clinit>(JSR223TestElement.java:61)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/JSR223PostProcessor
line number         : 147
version             : 0.64.3
-------------------------------
        at org.apache.jmeter.save.SaveService.readTree(SaveService.java:456)
        at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:429)
        at us.abstracta.jmeter.javadsl.core.engines.JmeterEnvironment.loadTree(JmeterEnvironment.java:115)
        at us.abstracta.jmeter.javadsl.codegeneration.DslCodeGenerator.buildMethodCallFromJmxFile(DslCodeGenerator.java:154)
        at us.abstracta.jmeter.javadsl.codegeneration.DslCodeGenerator.generateCodeFromJmx(DslCodeGenerator.java:148)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.call(Jmx2Dsl.java:44)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.call(Jmx2Dsl.java:17)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at us.abstracta.jmeter.javadsl.jmx2dsl.Jmx2Dsl.main(Jmx2Dsl.java:56)
Caused by: com.thoughtworks.xstream.converters.ConversionException:
---- Debugging information ----
cause-exception     : java.lang.NoClassDefFoundError
cause-message       : org/apache/commons/collections4/map/LRUMap
first-jmeter-class  : org.apache.jmeter.util.JSR223TestElement.<clinit>(JSR223TestElement.java:61)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/JSR223PostProcessor
line number         : 147
version             : 0.64.3
-------------------------------
        at org.apache.jmeter.save.ScriptWrapperConverter.createConversionException(ScriptWrapperConverter.java:101)
        at org.apache.jmeter.save.ScriptWrapperConverter.unmarshal(ScriptWrapperConverter.java:95)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1284)
        at org.apache.jmeter.save.SaveService.readTree(SaveService.java:446)
        ... 15 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections4/map/LRUMap
        at org.apache.jmeter.util.JSR223TestElement.<clinit>(JSR223TestElement.java:61)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.apache.jmeter.save.converters.TestElementConverter.unmarshal(TestElementConverter.java:102)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
        at org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
        at org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
        at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
        at org.apache.jmeter.save.ScriptWrapperConverter.unmarshal(ScriptWrapperConverter.java:93)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections4.map.LRUMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 48 more
`

**Comment by vrrocket** [comment]
There are no issues while opening jmx file in jmeter

**Comment by rabelenda** [comment]
Hello, thank you for reporting this.

Can you share an example of JMX that generates this (feel free to remove any non relevant or potential sensitive info)? Just want to make sure that after solving this particular problem you don't face another one and solve the conversion for your scenario :).

Regards

**Comment by rabelenda** [comment]
We have just released a [new version](https://github.com/abstracta/jmeter-java-dsl/releases/tag/v0.65) which should fix this problem. Please check it and let us know.

**Comment by vrrocket** [comment]
thanks for the update @rabelenda . Will check this version and let you know.
