### ISSUE TITLE
JTL file error

### ISSUE THREAD

**Issue by amitoverflow-ui** [abstracta/jmeter-java-dsl#16]
Getting below jtl file error when a test is executed:

org.apache.jmeter.reporters.ResultCollector - Exception occurred while initializing file output.
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[?:1.8.0_221]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[?:1.8.0_221]
	at java.io.File.getCanonicalPath(Unknown Source) ~[?:1.8.0_221]
	at org.apache.jmeter.reporters.ResultCollector.getFileWriter(ResultCollector.java:450) ~[ApacheJMeter_core-5.2.1.jar:5.2.1]
	at org.apache.jmeter.reporters.ResultCollector.testStarted(ResultCollector.java:325) ~[ApacheJMeter_core-5.2.1.jar:5.2.1]
	at org.apache.jmeter.reporters.ResultCollector.testStarted(ResultCollector.java:351) ~[ApacheJMeter_core-5.2.1.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:206) ~[ApacheJMeter_core-5.2.1.jar:5.2.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:381) ~[ApacheJMeter_core-5.2.1.jar:5.2.1]
	at us.abstracta.jmeter.javadsl.core.EmbeddedJmeterEngine.run(EmbeddedJmeterEngine.java:43) ~[jmeter-java-dsl-0.11.jar:?]
	at us.abstracta.jmeter.javadsl.core.DslTestPlan.run(DslTestPlan.java:36) ~[jmeter-java-dsl-0.11.jar:?]
	at pg.PerfTestJunit.testPerformance1(PerfTestJunit.java:37) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686) ~[org.junit.platform.commons_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71) ~[org.junit.jupiter.engine_5.6.0.v20200203-2009.jar:5.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_221]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_221]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) ~[org.junit.platform.engine_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248) ~[org.junit.platform.launcher_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211) ~[org.junit.platform.launcher_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226) [org.junit.platform.launcher_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199) [org.junit.platform.launcher_1.6.0.v20200203-2009.jar:1.6.0]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:141) [org.junit.platform.launcher_1.6.0.v20200203-2009.jar:1.6.0]
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]

**Sample test case:**
@Test
	  public void testPerformance1() throws IOException {		  
	    TestPlanStats stats = testPlan(
	      threadGroup(2, 10,
	        httpSampler("https://petstore.swagger.io/v2/pet/1").post("", Type.APPLICATION_JSON)
	      ),
	      jtlWriter("test" + Instant.now() + ".jtl")
	    ).run();
	    assertThat(stats.overall().elapsedTimePercentile99()).isLessThan(Duration.ofSeconds(5));
	  }

Apologies if I'm doing something wrong here.

**Comment by 3dgiordano** [comment]
@ankugarg 
As the exception mentions, the output format of Instant.now() not is valid for a Windows File System.
The problem is the colon character between hours, minutes and seconds, watch out for the period too.
Make sure to assign a filename that is valid for the file system.

**Comment by aabirdaneshyar** [comment]
@ankugarg ,
This problem is due to Instant.now()

Try using this -

`public void test() throws IOException {


		JsonObject postObject = Json.createObjectBuilder()
				.build();

		TestPlanStats stats = testPlan(
				threadGroup(1, 1,
						httpSampler("my-service")
						//.children(responseAssertion().containsSubstrings("201"))
						.header("Connection", "keep-alive")
						.post(postObject.toString(), Type.APPLICATION_JSON)),jtlWriter("test" + Math.random() + ".jtl"))
				.run();

		System.out.println("Error count is : " + stats.overall().errorsCount());
		System.out.println("Elapsed time by Jmeter DSL: " + stats.overall().elapsedTime().toMillis());
	}`

**Comment by rabelenda** [comment]
No need to ask for apologies, in fact this is consequence of provided examples not being good for windows systems. Thank you @3dgiordano & @aabirdaneshyar for pointing out the issue and a potential solutions. Here goes another solution:

```java
Instant.now().toString().replace(":","-")
```

I will update the documentation to avoid similar issues in the future.

**Comment by amitoverflow-ui** [comment]
Thanks for the info
