### ISSUE TITLE
Error when generating html report - report-template" is not a valid template directory

### ISSUE THREAD

**Issue by george-pc** [abstracta/jmeter-java-dsl#276]
I get below exception when generating html report with new versions
 Thee test has below statement to generate report 
```
                                                jtlWriter("target/jtl"))), //.withAllFields()))
                htmlReporter("reports"))
        .runIn(new EmbeddedJmeterEngine()
                        .propertiesFile(

```
It gives below error:
```

Caused by: org.apache.jmeter.report.dashboard.ExportException: "/var/folders/76/5xv5z5t91910d297gd84c8nh0000gn/T/jmeter-java-dsl4020534615103064137/bin/report-template" is not a valid template directory
	at org.apache.jmeter.report.dashboard.HtmlTemplateExporter.export(HtmlTemplateExporter.java:316) ~[jmeter-java-dsl-jmx2dsl-1.8.jar:1.8]
	at org.apache.jmeter.report.dashboard.ReportGenerator.exportData(ReportGenerator.java:382) ~[jmeter-java-dsl-jmx2dsl-1.8.jar:1.8]
	at org.apache.jmeter.report.dashboard.ReportGenerator.generate(ReportGenerator.java:260) ~[jmeter-java-dsl-jmx2dsl-1.8.jar:1.8]
	at us.abstracta.jmeter.javadsl.core.listeners.HtmlReporter$HtmlReportSummariser.testEnded(HtmlReporter.java:167) ~[jmeter-java-dsl-1.29.jar:1.29]
	... 82 more
```

**Comment by rabelenda** [comment]
Hello, thank you for reporting this. 

What do you mean by "with new versions"? Can you provide details on what versions you tested you don't get the error and in what versions you do?

**Comment by george-pc** [comment]
This error seems to have gone by removing the below explict dependancy to new version of ApacheJMeter_config in pom file. I commented below in my pom file and this resolved.
