### ISSUE TITLE
Bug - Exception when used in containerized application

### ISSUE THREAD

**Issue by mandarghatge** [abstracta/jmeter-java-dsl#285]
Created Spring boot application with jmeter-java-dsl 1.29.1 as compile time dependency (trying out some things so need to have this as compile scope instead of test)

Main application file executes a test, it works fine, but when the app is containerized, it throws an exception - 

Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.base/java.io.File.<init>(File.java:424)
        at us.abstracta.jmeter.javadsl.core.engines.JmeterEnvironment.getClassJarPath(JmeterEnvironment.java:96)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1716)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
        at us.abstracta.jmeter.javadsl.core.engines.JmeterEnvironment.updateSearchPath(JmeterEnvironment.java:70)
        at us.abstracta.jmeter.javadsl.core.engines.EmbeddedJmeterEngine.runInEnv(EmbeddedJmeterEngine.java:111)
        at us.abstracta.jmeter.javadsl.core.engines.EmbeddedJmeterEngine.run(EmbeddedJmeterEngine.java:93)
        at us.abstracta.jmeter.javadsl.core.DslTestPlan.run(DslTestPlan.java:138)

class **JmeterEnvironment**  - method - private String **getClassJarPath**(Class<?> theClass) throws an Exception - 

return new File(
          theClass.getProtectionDomain().getCodeSource().getLocation().toURI()).getPath();

Changing this code to - ( call toString() after toURI() ) seems to fix the problem -

return new File(
          theClass.getProtectionDomain().getCodeSource().getLocation().toURI()**.toString()**).getPath();

**Comment by rabelenda** [comment]
Hello, have you tried [this](https://github.com/abstracta/jmeter-java-dsl/issues/174)?

**Comment by mandarghatge** [comment]
Thank you for quick response, <requiresUnpack>....</requiresUnpack> worked !!
